### ISSUE TITLE
Need little clarification on this GetByExpression.

### ISSUE THREAD

**Issue by akshay-zz** [AhmedTarekHasan/BetterRepository#1]
`GetByExpression(Expression<Func<TEntity, bool>> predicate)`
By allowing the service/consumer to write the query. Aren't we moving away the queries to the service layer? Now the same query will be repeated every time when will try to fetch the data in different places. Can you please clarify this for me?

**Comment by AhmedTarekHasan** [comment]
Hi Akshay,

Indeed, and this is intended. The query represents business rules and logic and that's why it should reside on the service layer. Besides, we are not specifying the query in terms of how to access the database for example, we are just specifying the terms describing how to compose the query.

If you want to read more about this, try to search for "Specification Pattern". It is mainly concerned about the same topic.

Hope this answers your question 🙂


Best regards,
Ahmed Tarek
________________________________
From: akshay-zz ***@***.***>
Sent: Tuesday, August 16, 2022 9:31 AM
To: AhmedTarekHasan/BetterRepository ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AhmedTarekHasan/BetterRepository] Need little clarification on this GetByExpression(Expression<Func<TEntity, bool>> predicate). (Issue #1)


By allowing the service/consumer to write the query. Aren't we moving away the queries to the service layer? Now the same query will be repeated every time when will try to fetch the data in different places. Can you please clarify this for me?

**Comment by akshay-zz** [comment]
Will it be a good idea to have a query layer between the service and repository layer? So that all the DB-related queries reside in one place(mostly **get** I guess)?

**Comment by AhmedTarekHasan** [comment]
It could be a good idea and this again leads us to the Specification Pattern 🙂


Best regards,
Ahmed Tarek
________________________________
